env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - fp
extends: 'plugin:fp/recommended'
rules:
  indent:
    - off
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-spacing:
    - error
    - { "before": false, "after": true }
  func-call-spacing:
    - error
    - always
    - { "allowNewlines": true }
  no-unexpected-multiline:
    - off
  array-bracket-spacing:
    - error
    - always
  arrow-body-style:
    - error
    - never
  prefer-arrow-callback:
    - error
    - { allowNamedFunctions: false, allowUnboundThis: false }
  no-var:
    - error
  prefer-const:
    - error
  prefer-template:
    - error
  comma-dangle:
    - error
    - never
  no-ternary:
    - error
  fp/no-mutation:
    - error
    - { commonjs: true }
  fp/no-unused-expression:
    - off
overrides:
  files: [".mjs"]
