env:
  es6: true
  node: true
  jest: true
  browser: false
extends: airbnb-base
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
  - error
  - 2
  - { flatTernaryExpressions: true }
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - single
  semi:
  - error
  - never
  comma-dangle:
  - error
  - never
  prefer-template: error
  prefer-promise-reject-errors: off
  array-bracket-spacing:
  - error
  - always
  camelcase: warn
  no-confusing-arrow: off
  no-useless-escape: warn
  no-nested-ternary: off
  no-sequences: off
  no-plusplus: off
  no-shadow: off
  implicit-arrow-linebreak: off
  import/no-extraneous-dependencies: warn
  import/prefer-default-export: off
  max-len: warn
  arrow-parens: [error, as-needed]
  prefer-object-spread: off